### ISSUE TITLE
Why is this error been thrown when I run jslint using grunt to improve my code quality?

### ISSUE THREAD

**Issue by yegya** [stephenmathieson/grunt-jslint#55]
At this line jslint throws an error
window.__wbuxq = __wbux;

I see this error:
Expected ';' and instead saw '.'

Why does it expect ; after window when that should not be the case?

**Comment by smikes** [comment]
I can't answer that question, because jslint seems to be using context from the previous line to decide that.  When I test just the line above against the online linter at http://www.jslint.com/, I don't see any message about "Expected ';'...", so I believe this is caused by something on a previous line.

In general, you should know that this project is just the bridge between `grunt` and `jslint`.  If you have questions about how `jslint` works, you should post to the google group for jslint, https://plus.google.com/u/0/communities/104441363299760713736?cfem=1

**Comment by yegya** [comment]
Okay thanx for the response.
